package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"
	"unicode"
)

type schemaDocument struct {
	Description string                 `json:"description"`
	Properties  map[string]*schemaNode `json:"properties"`
	Required    []string               `json:"required"`
	Definitions map[string]*schemaNode `json:"definitions"`
}

type schemaNode struct {
	Description          string                 `json:"description"`
	Ref                  string                 `json:"$ref"`
	Type                 any                    `json:"type"`
	Properties           map[string]*schemaNode `json:"properties"`
	Required             []string               `json:"required"`
	Items                *schemaNode            `json:"items"`
	AdditionalProperties any                    `json:"additionalProperties"`
	Enum                 []any                  `json:"enum"`
	Default              any                    `json:"default"`
}

var initialism = map[string]string{
	"guid": "GUID",
	"html": "HTML",
	"id":   "ID",
	"ids":  "IDs",
	"uri":  "URI",
	"uris": "URIs",
	"url":  "URL",
}

func main() {
	schemaPath := flag.String("schema", "", "path to SARIF JSON schema")
	outPath := flag.String("out", "", "generated Go file path")
	flag.Parse()

	if *schemaPath == "" || *outPath == "" {
		log.Fatal("both -schema and -out are required")
	}

	data, err := os.ReadFile(*schemaPath)
	if err != nil {
		log.Fatal(err)
	}

	var doc schemaDocument
	if err := json.Unmarshal(data, &doc); err != nil {
		log.Fatal(err)
	}

	src, err := generate(&doc)
	if err != nil {
		log.Fatal(err)
	}

	formatted, err := format.Source(src)
	if err != nil {
		_, _ = os.Stderr.Write(src)
		log.Fatal(err)
	}

	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		log.Fatal(err)
	}
}

func generate(doc *schemaDocument) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	b.WriteString("package sarif\n\n")
	b.WriteString("import \"encoding/json\"\n\n")
	writeType(&b, "Log", doc.Description, &schemaNode{
		Properties: doc.Properties,
		Required:   doc.Required,
	})

	names := make([]string, 0, len(doc.Definitions))
	for name := range doc.Definitions {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		if name == "propertyBag" {
			b.WriteString("// PropertyBag contains arbitrary extension properties.\n")
			b.WriteString("type PropertyBag map[string]any\n\n")
			continue
		}
		writeType(&b, goTypeName(name), doc.Definitions[name].Description, doc.Definitions[name])
	}

	return b.Bytes(), nil
}

func writeType(b *bytes.Buffer, typeName string, description string, node *schemaNode) {
	keys := orderedPropertyNames(node.Properties)
	hasDefaults := len(defaultPropertyNames(keys, node.Properties)) > 0
	writeComment(b, typeName, description)
	if hasDefaults {
		fmt.Fprintf(b, "// Use New%s when constructing a value so schema defaults are initialized.\n", typeName)
	}
	b.WriteString("type ")
	b.WriteString(typeName)
	b.WriteString(" struct {\n")

	required := requiredSet(node.Required)
	for _, jsonName := range keys {
		prop := node.Properties[jsonName]
		fieldName := goFieldName(jsonName)
		fieldType := goType(prop)
		tag := jsonName
		if !required[jsonName] {
			tag += ",omitempty,omitzero"
		}
		writeComment(b, fieldName, prop.Description)
		fmt.Fprintf(b, "\t%s %s `json:\"%s\"`\n", fieldName, fieldType, tag)
	}
	b.WriteString("}\n\n")

	writeConstructor(b, typeName, keys, node.Properties)
	writeMarshalJSON(b, typeName, keys, node.Properties, required)
	writeUnmarshalJSON(b, typeName, keys, node.Properties)
}

func writeConstructor(b *bytes.Buffer, typeName string, keys []string, properties map[string]*schemaNode) {
	defaults := defaultPropertyNames(keys, properties)
	if len(defaults) == 0 {
		return
	}

	fmt.Fprintf(b, "// New%s returns an initialized %s with the defaults defined by SARIF 2.1.0.\n", typeName, typeName)
	fmt.Fprintf(b, "func New%s() %s {\n", typeName, typeName)
	fmt.Fprintf(b, "\treturn %s{\n", typeName)
	for _, jsonName := range defaults {
		fmt.Fprintf(b, "\t\t%s: %s,\n", goFieldName(jsonName), defaultLiteral(properties[jsonName]))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
}

func writeMarshalJSON(b *bytes.Buffer, typeName string, keys []string, properties map[string]*schemaNode, required map[string]bool) {
	fmt.Fprintf(b, "func (v %s) MarshalJSON() ([]byte, error) {\n", typeName)
	b.WriteString("\tfields := make(map[string]any)\n")
	for _, jsonName := range keys {
		fieldName := goFieldName(jsonName)
		prop := properties[jsonName]
		if required[jsonName] {
			fmt.Fprintf(b, "\tfields[%q] = v.%s\n", jsonName, fieldName)
			continue
		}
		if hasDefault(prop) {
			fmt.Fprintf(b, "\tif includeNonDefault(v.%s, %s) {\n", fieldName, defaultLiteral(prop))
		} else {
			fmt.Fprintf(b, "\tif includeNonZero(v.%s) {\n", fieldName)
		}
		fmt.Fprintf(b, "\t\tfields[%q] = v.%s\n", jsonName, fieldName)
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn json.Marshal(fields)\n")
	b.WriteString("}\n\n")
}

func writeUnmarshalJSON(b *bytes.Buffer, typeName string, keys []string, properties map[string]*schemaNode) {
	defaults := defaultPropertyNames(keys, properties)
	if len(defaults) == 0 {
		return
	}

	fmt.Fprintf(b, "func (v *%s) UnmarshalJSON(data []byte) error {\n", typeName)
	fmt.Fprintf(b, "\ttype alias %s\n", typeName)
	fmt.Fprintf(b, "\ttmp := alias(New%s())\n", typeName)
	b.WriteString("\tif err := json.Unmarshal(data, &tmp); err != nil {\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n")
	fmt.Fprintf(b, "\t*v = %s(tmp)\n", typeName)
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
}

func defaultPropertyNames(keys []string, properties map[string]*schemaNode) []string {
	defaults := make([]string, 0)
	for _, jsonName := range keys {
		if hasDefault(properties[jsonName]) {
			defaults = append(defaults, jsonName)
		}
	}
	return defaults
}

func hasDefault(node *schemaNode) bool {
	return node != nil && node.Default != nil
}

func defaultLiteral(node *schemaNode) string {
	switch value := node.Default.(type) {
	case bool:
		if value {
			return "true"
		}
		return "false"
	case float64:
		if schemaType(node) == "integer" {
			return fmt.Sprintf("%d", int(value))
		}
		return fmt.Sprintf("float64(%#v)", value)
	case string:
		return fmt.Sprintf("%q", value)
	case []any:
		items := make([]string, 0, len(value))
		for _, item := range value {
			switch v := item.(type) {
			case string:
				items = append(items, fmt.Sprintf("%q", v))
			case float64:
				items = append(items, fmt.Sprintf("%#v", v))
			case bool:
				if v {
					items = append(items, "true")
				} else {
					items = append(items, "false")
				}
			}
		}
		return goType(node) + "{" + strings.Join(items, ", ") + "}"
	default:
		return "nil"
	}
}

func orderedPropertyNames(properties map[string]*schemaNode) []string {
	keys := make([]string, 0, len(properties))
	for key := range properties {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func requiredSet(required []string) map[string]bool {
	set := make(map[string]bool, len(required))
	for _, name := range required {
		set[name] = true
	}
	return set
}

func goType(node *schemaNode) string {
	if node == nil {
		return "any"
	}
	if node.Ref != "" {
		return refType(node.Ref)
	}
	if schemaType(node) == "array" {
		return "[]" + goType(node.Items)
	}
	if schemaType(node) == "object" {
		if addl, ok := additionalPropertiesSchema(node); ok {
			return "map[string]" + goType(addl)
		}
		if len(node.Properties) == 0 {
			return "map[string]any"
		}
		return "map[string]any"
	}
	if len(node.Enum) > 0 {
		return "string"
	}

	switch schemaType(node) {
	case "boolean":
		return "bool"
	case "integer":
		return "int"
	case "number":
		return "float64"
	case "string":
		return "string"
	default:
		return "any"
	}
}

func additionalPropertiesSchema(node *schemaNode) (*schemaNode, bool) {
	raw, ok := node.AdditionalProperties.(map[string]any)
	if !ok {
		return nil, false
	}
	data, err := json.Marshal(raw)
	if err != nil {
		return nil, false
	}
	var addl schemaNode
	if err := json.Unmarshal(data, &addl); err != nil {
		return nil, false
	}
	return &addl, true
}

func schemaType(node *schemaNode) string {
	switch v := node.Type.(type) {
	case string:
		return v
	case []any:
		for _, value := range v {
			if s, ok := value.(string); ok && s != "null" {
				return s
			}
		}
	}
	return ""
}

func refType(ref string) string {
	const prefix = "#/definitions/"
	return goTypeName(strings.TrimPrefix(ref, prefix))
}

func goTypeName(schemaName string) string {
	parts := splitName(schemaName)
	for i, part := range parts {
		parts[i] = exportPart(part)
	}
	return strings.Join(parts, "")
}

func goFieldName(jsonName string) string {
	if jsonName == "$schema" {
		return "SchemaURI"
	}
	return goTypeName(jsonName)
}

func splitName(name string) []string {
	runes := []rune(name)
	if len(runes) == 0 {
		return nil
	}

	var parts []string
	start := 0
	for i := 1; i < len(runes); i++ {
		prev := runes[i-1]
		cur := runes[i]
		var next rune
		if i+1 < len(runes) {
			next = runes[i+1]
		}

		boundary := false
		switch {
		case unicode.IsDigit(cur) != unicode.IsDigit(prev):
			boundary = true
		case unicode.IsUpper(cur) && (unicode.IsLower(prev) || unicode.IsDigit(prev)):
			boundary = true
		case unicode.IsUpper(cur) && unicode.IsUpper(prev) && next != 0 && unicode.IsLower(next):
			boundary = true
		}

		if boundary {
			parts = append(parts, string(runes[start:i]))
			start = i
		}
	}
	parts = append(parts, string(runes[start:]))
	return parts
}

func exportPart(part string) string {
	lower := strings.ToLower(part)
	if replacement, ok := initialism[lower]; ok {
		return replacement
	}
	runes := []rune(lower)
	if len(runes) == 0 {
		return ""
	}
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func writeComment(b *bytes.Buffer, name string, description string) {
	description = strings.TrimSpace(strings.Join(strings.Fields(description), " "))
	if description == "" {
		return
	}
	description = strings.TrimSuffix(description, ".")
	fmt.Fprintf(b, "// %s %s.\n", name, description)
}
